controller_manager:
  ros__parameters:
    update_rate: 100
    joint_state_controller:
      type:joint_state_controller/JointStateController
      publish_rate:50
    panda_arm_controller:
      type: position_controllers/JointTrajectoryController
      joints:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7
      gains:
        panda_joint1: {p: 100.0, d: 1.0, i: 0.01}
        panda_joint2: {p: 100.0, d: 1.0, i: 0.01}
        panda_joint3: {p: 100.0, d: 1.0, i: 0.01}
        panda_joint4: {p: 100.0, d: 1.0, i: 0.01}
        panda_joint5: {p: 100.0, d: 1.0, i: 0.01}
        panda_joint6: {p: 100.0, d: 1.0, i: 0.01}
        panda_joint7: {p: 100.0, d: 1.0, i: 0.01}
        
        
        

